### ISSUE TITLE
Replacing an entire file does not function multiline

### ISSUE THREAD

**Issue by bdebaere** [knom/vsts-regex-tasks#19] opened 2019-02-25 00:03 UTC
Using ^[\s\S]*$ to replace an entire file causes you to have a file with N lines of the replacement string, where N is the number of lines you have in your original config.

**Comment by aaimaai** [comment] 2019-06-04 13:20
I have the same issue. This is caused by how the contents of the file is read. 
`$text = Get-Content $path -Encoding UTF8`
messes up the new lines. This can be fixed by adding the -Raw option:
`$text = Get-Content $path -Encoding UTF8 -Raw`

**Comment by knom** [comment] 2019-10-23 07:08
This got merged now..
Closing.

**Closed by knom** 2019-10-23 07:08 UTC
